server:
  port: 8080
spring:
#  security:
#    user:
#      name: challenge
#      password: challenge
  application:
    name: challenge-crud-pix
  datasource:
    url: jdbc:mysql://localhost:3306/challenge
    username: root
    password: challenge
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true