server:
  port: 8181
spring:
#  security:
#    user:
#      name: challenge
#      password: challenge
  application:
    name: microservice
  datasource:
    url: jdbc:oracle:thin:@localhost:${{ job.services.oracle.ports[1521] }}/FREEPDB1
    username: my_user
    password: password_i_should_change
  flyway:
    enabled: true
  jenkins:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true