version: '3.9'

services:
  datasource:
    image: gvenzl/oracle-free:latest
    container_name: oracle
    restart: always
    environment:
      ORACLE_DATABESE: 'PDB1'
      ORACLE_PASSWORD: 'sys_user_password'
      APP_USER: 'my_user'
      APP_USER_PASSWORD: 'password_i_should_change'
    ports:
      - '1521:1521'
    volumes:
      - oracle-data:/opt/oracle/oracleDb
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "@healthcheck.sql"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - network_datasource
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - network_jenkins
    volumes:
      - jenkins:/var/lib/jenkins
networks:
  network_datasource:
    driver: bridge
  network_jenkins:
    driver: bridge
volumes:
  oracle-data:
  oracle-backup:
  jenkins:
