version: '3.9'

services:
  datasource:
    image: mysql:8.3-oraclelinux8
    container_name: datasource
    restart: always
    environment:
      MYSQL_USER: 'challenge'
      MYSQL_DATABASE: 'challenge'
      MYSQL_PASSWORD: 'challenge'
      MYSQL_ROOT_PASSWORD: 'challenge'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - network_challenge
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - '8181:8080'
      - '50000:50000'
    volumes:
      - /home/usertqi/jenkins
networks:
  network_challenge:
    driver: bridge
volumes:
  my-db:
