pipeline{
    agent any
    stages{
        stage ("Build"){
            steps {
                sh 'gradle build'

            }

        }
        stage ("Middle"){
            steps{
                sh 'echo middle'
            }
        }
        stage ("End"){
            steps{
                sleep(30)
                sh 'echo this is all folks...'
            }
        }


        }

    }
    }